# Generated by Django 6.0 on 2025-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=10, help_text='Duration in minutes'),
        ),
    ]
